// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/trade.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'signal.freezed.dart';

@freezed
sealed class Signal with _$Signal {
  const Signal._();

  /// Enter a long position.
  const factory Signal.enterLong({
    /// Stop loss price (absolute).
    double? sl,

    /// Take profit price (absolute).
    double? tp,

    /// Position size as a percentage of available capital (0.0 - 100.0).
    required double sizePct,
  }) = Signal_EnterLong;

  /// Enter a short position.
  const factory Signal.enterShort({
    /// Stop loss price (absolute).
    double? sl,

    /// Take profit price (absolute).
    double? tp,

    /// Position size as a percentage of available capital (0.0 - 100.0).
    required double sizePct,
  }) = Signal_EnterShort;

  /// Exit the current position.
  const factory Signal.exit({
    /// Reason for exiting.
    required ExitReason reason,
  }) = Signal_Exit;

  /// Move the stop loss to a new price level.
  const factory Signal.moveStop({
    /// New stop loss price (absolute).
    required double newSl,
  }) = Signal_MoveStop;

  /// No action taken this candle.
  const factory Signal.noAction() = Signal_NoAction;
}
