// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models/candle.dart';
import 'models/trade.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'strategy/signal.dart';

/// Returns the engine version string.
Future<String> getVersion() => RustLib.instance.api.crateApiGetVersion();

/// Simple ping function to verify the bridge is working.
Future<String> ping() => RustLib.instance.api.crateApiPing();

/// Create a test candle to verify data structure serialization across the bridge.
Future<Candle> createTestCandle() =>
    RustLib.instance.api.crateApiCreateTestCandle();

/// Test signal creation - returns a sample EnterLong signal.
Future<Signal> createTestSignalLong() =>
    RustLib.instance.api.crateApiCreateTestSignalLong();

/// Test signal creation - returns a sample EnterShort signal.
Future<Signal> createTestSignalShort() =>
    RustLib.instance.api.crateApiCreateTestSignalShort();

/// Test creating a NoAction signal.
Future<Signal> createTestSignalNoAction() =>
    RustLib.instance.api.crateApiCreateTestSignalNoAction();

/// Verify that a candle can round-trip through JSON serialization.
Future<String> roundtripCandleJson({required Candle candle}) =>
    RustLib.instance.api.crateApiRoundtripCandleJson(candle: candle);

/// Get the list of supported timeframes.
Future<List<String>> getSupportedTimeframes() =>
    RustLib.instance.api.crateApiGetSupportedTimeframes();

/// Get a sample strategy manifest (for testing the manifest data flow).
Future<String> getSampleManifest() =>
    RustLib.instance.api.crateApiGetSampleManifest();

/// Validate that a signal is actionable.
Future<bool> isSignalActionable({required String signalJson}) =>
    RustLib.instance.api.crateApiIsSignalActionable(signalJson: signalJson);

/// Get the BB+RSI strategy manifest as JSON.
Future<String> getBbRsiManifest() =>
    RustLib.instance.api.crateApiGetBbRsiManifest();

/// Run the BB+RSI strategy on a list of candles (JSON in, JSON out).
///
/// `candles_json` – JSON array of candle objects.
/// `params_json`  – JSON object with parameter overrides (e.g. `{"bb_period": 25}`).
///
/// Returns a JSON array of objects `{ "index": N, "signal": <Signal> }` for every
/// actionable signal the strategy emitted.
Future<String> runBbRsiStrategy({
  required String candlesJson,
  required String paramsJson,
}) => RustLib.instance.api.crateApiRunBbRsiStrategy(
  candlesJson: candlesJson,
  paramsJson: paramsJson,
);

/// Run a full backtest of the BB+RSI strategy on historical candles.
///
/// `candles_json`    – JSON array of `Candle` objects.
/// `params_json`     – JSON object with parameter overrides (e.g. `{"bb_period": 25}`).
/// `initial_balance` – Starting account balance in quote currency (e.g. 10000.0 USDT).
/// `fee_rate`        – Taker fee rate per side (e.g. 0.0006 for Bitunix VIP0 0.06 %).
///
/// Returns a JSON-serialised `BacktestResult` containing metrics, equity curve,
/// trade log, and fee summary – ready for Flutter consumption.
Future<String> runBbRsiBacktest({
  required String candlesJson,
  required String paramsJson,
  required double initialBalance,
  required double feeRate,
}) => RustLib.instance.api.crateApiRunBbRsiBacktest(
  candlesJson: candlesJson,
  paramsJson: paramsJson,
  initialBalance: initialBalance,
  feeRate: feeRate,
);
