// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models/candle.dart';
import 'models/trade.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'strategy/signal.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -3652998;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'trading_engine',
        ioDirectory: 'rust/trading_engine/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Candle> crateApiCreateTestCandle();

  Future<Signal> crateApiCreateTestSignalLong();

  Future<Signal> crateApiCreateTestSignalNoAction();

  Future<Signal> crateApiCreateTestSignalShort();

  Future<String> crateApiGetBbRsiManifest();

  Future<String> crateApiGetSampleManifest();

  Future<List<String>> crateApiGetSupportedTimeframes();

  Future<String> crateApiGetVersion();

  Future<bool> crateApiIsSignalActionable({required String signalJson});

  Future<String> crateApiPing();

  Future<String> crateApiRoundtripCandleJson({required Candle candle});

  Future<String> crateApiRunBbRsiBacktest({
    required String candlesJson,
    required String paramsJson,
    required double initialBalance,
    required double feeRate,
  });

  Future<String> crateApiRunBbRsiStrategy({
    required String candlesJson,
    required String paramsJson,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Candle> crateApiCreateTestCandle() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_candle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCreateTestCandleConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateTestCandleConstMeta =>
      const TaskConstMeta(debugName: "create_test_candle", argNames: []);

  @override
  Future<Signal> crateApiCreateTestSignalLong() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signal,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCreateTestSignalLongConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateTestSignalLongConstMeta =>
      const TaskConstMeta(debugName: "create_test_signal_long", argNames: []);

  @override
  Future<Signal> crateApiCreateTestSignalNoAction() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signal,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCreateTestSignalNoActionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateTestSignalNoActionConstMeta =>
      const TaskConstMeta(
        debugName: "create_test_signal_no_action",
        argNames: [],
      );

  @override
  Future<Signal> crateApiCreateTestSignalShort() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signal,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCreateTestSignalShortConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateTestSignalShortConstMeta =>
      const TaskConstMeta(debugName: "create_test_signal_short", argNames: []);

  @override
  Future<String> crateApiGetBbRsiManifest() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetBbRsiManifestConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetBbRsiManifestConstMeta =>
      const TaskConstMeta(debugName: "get_bb_rsi_manifest", argNames: []);

  @override
  Future<String> crateApiGetSampleManifest() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetSampleManifestConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSampleManifestConstMeta =>
      const TaskConstMeta(debugName: "get_sample_manifest", argNames: []);

  @override
  Future<List<String>> crateApiGetSupportedTimeframes() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetSupportedTimeframesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSupportedTimeframesConstMeta =>
      const TaskConstMeta(debugName: "get_supported_timeframes", argNames: []);

  @override
  Future<String> crateApiGetVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetVersionConstMeta =>
      const TaskConstMeta(debugName: "get_version", argNames: []);

  @override
  Future<bool> crateApiIsSignalActionable({required String signalJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(signalJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIsSignalActionableConstMeta,
        argValues: [signalJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIsSignalActionableConstMeta => const TaskConstMeta(
    debugName: "is_signal_actionable",
    argNames: ["signalJson"],
  );

  @override
  Future<String> crateApiPing() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPingConstMeta =>
      const TaskConstMeta(debugName: "ping", argNames: []);

  @override
  Future<String> crateApiRoundtripCandleJson({required Candle candle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_candle(candle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRoundtripCandleJsonConstMeta,
        argValues: [candle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRoundtripCandleJsonConstMeta =>
      const TaskConstMeta(
        debugName: "roundtrip_candle_json",
        argNames: ["candle"],
      );

  @override
  Future<String> crateApiRunBbRsiBacktest({
    required String candlesJson,
    required String paramsJson,
    required double initialBalance,
    required double feeRate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(candlesJson, serializer);
          sse_encode_String(paramsJson, serializer);
          sse_encode_f_64(initialBalance, serializer);
          sse_encode_f_64(feeRate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRunBbRsiBacktestConstMeta,
        argValues: [candlesJson, paramsJson, initialBalance, feeRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunBbRsiBacktestConstMeta => const TaskConstMeta(
    debugName: "run_bb_rsi_backtest",
    argNames: ["candlesJson", "paramsJson", "initialBalance", "feeRate"],
  );

  @override
  Future<String> crateApiRunBbRsiStrategy({
    required String candlesJson,
    required String paramsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(candlesJson, serializer);
          sse_encode_String(paramsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRunBbRsiStrategyConstMeta,
        argValues: [candlesJson, paramsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunBbRsiStrategyConstMeta => const TaskConstMeta(
    debugName: "run_bb_rsi_strategy",
    argNames: ["candlesJson", "paramsJson"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Candle dco_decode_box_autoadd_candle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_candle(raw);
  }

  @protected
  ExitReason dco_decode_box_autoadd_exit_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_exit_reason(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Candle dco_decode_candle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Candle(
      timestamp: dco_decode_i_64(arr[0]),
      open: dco_decode_f_64(arr[1]),
      high: dco_decode_f_64(arr[2]),
      low: dco_decode_f_64(arr[3]),
      close: dco_decode_f_64(arr[4]),
      volume: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  ExitReason dco_decode_exit_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ExitReason_StopLoss();
      case 1:
        return ExitReason_TakeProfit();
      case 2:
        return ExitReason_Signal(dco_decode_String(raw[1]));
      case 3:
        return ExitReason_Manual();
      case 4:
        return ExitReason_EndOfData();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  Signal dco_decode_signal(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Signal_EnterLong(
          sl: dco_decode_opt_box_autoadd_f_64(raw[1]),
          tp: dco_decode_list_prim_f_64_strict(raw[2]),
          sizePct: dco_decode_f_64(raw[3]),
        );
      case 1:
        return Signal_EnterShort(
          sl: dco_decode_opt_box_autoadd_f_64(raw[1]),
          tp: dco_decode_list_prim_f_64_strict(raw[2]),
          sizePct: dco_decode_f_64(raw[3]),
        );
      case 2:
        return Signal_Exit(reason: dco_decode_box_autoadd_exit_reason(raw[1]));
      case 3:
        return Signal_MoveStop(newSl: dco_decode_f_64(raw[1]));
      case 4:
        return Signal_NoAction();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Candle sse_decode_box_autoadd_candle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_candle(deserializer));
  }

  @protected
  ExitReason sse_decode_box_autoadd_exit_reason(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_exit_reason(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  Candle sse_decode_candle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_open = sse_decode_f_64(deserializer);
    var var_high = sse_decode_f_64(deserializer);
    var var_low = sse_decode_f_64(deserializer);
    var var_close = sse_decode_f_64(deserializer);
    var var_volume = sse_decode_f_64(deserializer);
    return Candle(
      timestamp: var_timestamp,
      open: var_open,
      high: var_high,
      low: var_low,
      close: var_close,
      volume: var_volume,
    );
  }

  @protected
  ExitReason sse_decode_exit_reason(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ExitReason_StopLoss();
      case 1:
        return ExitReason_TakeProfit();
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return ExitReason_Signal(var_field0);
      case 3:
        return ExitReason_Manual();
      case 4:
        return ExitReason_EndOfData();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Signal sse_decode_signal(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_sl = sse_decode_opt_box_autoadd_f_64(deserializer);
        var var_tp = sse_decode_list_prim_f_64_strict(deserializer);
        var var_sizePct = sse_decode_f_64(deserializer);
        return Signal_EnterLong(sl: var_sl, tp: var_tp, sizePct: var_sizePct);
      case 1:
        var var_sl = sse_decode_opt_box_autoadd_f_64(deserializer);
        var var_tp = sse_decode_list_prim_f_64_strict(deserializer);
        var var_sizePct = sse_decode_f_64(deserializer);
        return Signal_EnterShort(sl: var_sl, tp: var_tp, sizePct: var_sizePct);
      case 2:
        var var_reason = sse_decode_box_autoadd_exit_reason(deserializer);
        return Signal_Exit(reason: var_reason);
      case 3:
        var var_newSl = sse_decode_f_64(deserializer);
        return Signal_MoveStop(newSl: var_newSl);
      case 4:
        return Signal_NoAction();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_candle(Candle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_candle(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_exit_reason(
    ExitReason self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_exit_reason(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_candle(Candle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_f_64(self.open, serializer);
    sse_encode_f_64(self.high, serializer);
    sse_encode_f_64(self.low, serializer);
    sse_encode_f_64(self.close, serializer);
    sse_encode_f_64(self.volume, serializer);
  }

  @protected
  void sse_encode_exit_reason(ExitReason self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ExitReason_StopLoss():
        sse_encode_i_32(0, serializer);
      case ExitReason_TakeProfit():
        sse_encode_i_32(1, serializer);
      case ExitReason_Signal(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case ExitReason_Manual():
        sse_encode_i_32(3, serializer);
      case ExitReason_EndOfData():
        sse_encode_i_32(4, serializer);
    }
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_signal(Signal self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Signal_EnterLong(sl: final sl, tp: final tp, sizePct: final sizePct):
        sse_encode_i_32(0, serializer);
        sse_encode_opt_box_autoadd_f_64(sl, serializer);
        sse_encode_list_prim_f_64_strict(tp, serializer);
        sse_encode_f_64(sizePct, serializer);
      case Signal_EnterShort(
        sl: final sl,
        tp: final tp,
        sizePct: final sizePct,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_opt_box_autoadd_f_64(sl, serializer);
        sse_encode_list_prim_f_64_strict(tp, serializer);
        sse_encode_f_64(sizePct, serializer);
      case Signal_Exit(reason: final reason):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_exit_reason(reason, serializer);
      case Signal_MoveStop(newSl: final newSl):
        sse_encode_i_32(3, serializer);
        sse_encode_f_64(newSl, serializer);
      case Signal_NoAction():
        sse_encode_i_32(4, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
