// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Represents a single OHLCV candlestick.
class Candle {
  /// Unix timestamp in milliseconds.
  final PlatformInt64 timestamp;

  /// Opening price.
  final double open;

  /// Highest price during the period.
  final double high;

  /// Lowest price during the period.
  final double low;

  /// Closing price.
  final double close;

  /// Trading volume.
  final double volume;

  const Candle({
    required this.timestamp,
    required this.open,
    required this.high,
    required this.low,
    required this.close,
    required this.volume,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^
      open.hashCode ^
      high.hashCode ^
      low.hashCode ^
      close.hashCode ^
      volume.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Candle &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          open == other.open &&
          high == other.high &&
          low == other.low &&
          close == other.close &&
          volume == other.volume;
}
